#!/usr/bin/env bash
set -euo pipefail

API_BASE_URL="${API_BASE_URL:-http://localhost:3000}"
API_KEY="${API_KEY:-}"

PERSONA_INTEGRATION_ID="${PERSONA_INTEGRATION_ID:-}"
XMTP_INTEGRATION_ID="${XMTP_INTEGRATION_ID:-}"
OFFRAMP_INTEGRATION_ID="${OFFRAMP_INTEGRATION_ID:-}"
SUPERCHAIN_INTEGRATION_ID="${SUPERCHAIN_INTEGRATION_ID:-}"
REQUEST_FINANCE_INTEGRATION_ID="${REQUEST_FINANCE_INTEGRATION_ID:-}"

XMTP_RECIPIENT_ADDRESS="${XMTP_RECIPIENT_ADDRESS:-}"
WALLET_ADDRESS="${WALLET_ADDRESS:-}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"
XMTP_DB_PATH="${XMTP_DB_PATH:-/private/tmp/keeperhub-xmtp}"
FORCE_FULL_PATH="${FORCE_FULL_PATH:-0}"
TEST_INVOICE_AMOUNT="${TEST_INVOICE_AMOUNT:-20}"

if [[ -z "${API_KEY}" ]]; then
